spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudaware_db
    username: cloudaware
    password: cloudaware
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    database: postgresql
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true